### ISSUE TITLE
HUD changes Position automatically 

### ISSUE THREAD

**Issue by LS-Friend** [stijnwop/proSeed#14]
Hello guys,
does anyone of you have the same problem like me? CPU changes HUD-position of ProSeed-HUD automatically after many restarts (mostly when I play FS a few days later), without having done any new settings or something like that. I tried deleting the ProSeed XML and giving new coordinates for „x“ and „y“, but CPU doesn’t hold ProSeed-HUD constant. The coordinates in XML are always changed automatically then (values overwritten). I‘m playing with the newest versions of ProSeed from github and Giants FS Patches. Can you help me?

**Comment by mrPassion78** [comment]
i have a similarly  thing.. the Hud changes the position to " off-screen"  value, and before i start a savegame, i delete the Proseed xml from the savegame, and than it shows up at the vanilla position, when starting the savegame.
i have to repeat that with EVERY start of the savegame.
