### ISSUE TITLE
ProSeed mit Courseplay nutzen

### ISSUE THREAD

**Issue by Hartmut88** [stijnwop/proSeed#16]
Hallo Leute,

kann man irgendwie etwas tun, damit ProSeed sauber mit CP zusammenarbeitet?
Fehler, welche mir aufgefallen sind: 
- sobald man CP aktiviert, verschwindet das HUD
- beim ProSeed Modus "Auto" funktioniert zwar alles, jedoch nur solange man selbst im Traktor sitzt. Steigt man aus, werden die 
   Spuren nicht weiter geschaltet

**Comment by stijnwop** [comment]
Should work.
