### ISSUE TITLE
Manure System und Proseed werden nicht im spiel angezeigt

### ISSUE THREAD

**Issue by fischi3016** [stijnwop/proSeed#18]
![fsScreen_2020_07_24_15_02_14](https://user-images.githubusercontent.com/63921968/88393891-bdcc8900-cdbe-11ea-9ffd-60b587f2c98f.png)
![fsScreen_2020_07_24_15_02_18](https://user-images.githubusercontent.com/63921968/88393892-be651f80-cdbe-11ea-895c-5ddb3d5da9b0.png)
![Unbenannt](https://user-images.githubusercontent.com/63921968/88393898-c1f8a680-cdbe-11ea-8856-64ea22f2b4d2.PNG)

Hab beide mods wie beschrieben in den Modordner gelegt und wenn ich spiel Starte sind beide Mods nicht auswählbar

**Comment by KITT3000** [comment]
Do you have patch 1.6 installed?

**Comment by fischi3016** [comment]
No!

the newest patch on steam is 1.5.1

**Comment by KITT3000** [comment]
Farming Simulator 19 (Steam)
  Version: 1.6.0.0 b9173

**Comment by KITT3000** [comment]
This is an option to roll back to the previous version, select the first option.

**Comment by fischi3016** [comment]
thx =)

have a nice weekend
