### ISSUE TITLE
Measurement accuracy

### ISSUE THREAD

**Issue by Gonimy-Vetrom** [stijnwop/proSeed#19]
It seems to me that there is some mistake in calculating the seeding rate.
This field was sown in approximately 2 hours. Then the seeding rate should be about 10 ha/hour. But not 2.6!
![fsScreen_2020_09_09_23_49_58](https://user-images.githubusercontent.com/8200153/92781506-dc0d3900-f3ac-11ea-9dab-cf36f9eee374.png)

**Comment by stijnwop** [comment]
Believe the issue is that the hectare time was not reset for the current session which means you had more hectare time on your seeder from previous sessions resulting in the lower ha/h.

**Comment by Gonimy-Vetrom** [comment]
I did the reset because I specifically wanted to know the area of my new jointed fields.

**Comment by stijnwop** [comment]
Yes, I did not reset the hectare time.. pushed a fix ^ see above. So that's probably why it resulted in the lower value cause it had the old time on it.

**Comment by Gonimy-Vetrom** [comment]
Probably. Because on the new sowing machine, I remember it was 20-25 hectares / hour.

**Comment by Gonimy-Vetrom** [comment]
Thank you. The problem has been resolved.
