### ISSUE TITLE
SeedUsage value is too small

### ISSUE THREAD

**Issue by Gonimy-Vetrom** [stijnwop/proSeed#21]
![fsScreen_2020_10_17_13_16_32](https://user-images.githubusercontent.com/8200153/96334731-99a9dc80-107b-11eb-8cc3-5fe69ecfc3c9.png)
Hey. As I understand it, the element highlighted in the picture is "SeedUsage".
But its value is so small that it is not very informative.
Is it possible to increase the number of signs after the dot or to make liters per 100 ha?

**Comment by Snickers125** [comment]
Highly recommended

**Comment by Gordon-Dry** [comment]
This is still an issue in the way that the shown rate is 10x smaller than the real seed usage is.
In my case it says "0.05l" which should mean "0.05 liters per second" which would be 20 seconds for one liter as the readout is refreshed once a second.
I can clearly see that the usage is 2 seconds for one liter, so exactly 10x higher.

It can't be "0.05l per sqm" as that's not what's defined in game.

**Comment by Gordon-Dry** [comment]
To make it clear, if 
src\vehicle\ProSeedSowingExtension.lua lines 419 and 429 should be liters per sqm, why is the value so off to what's defined?
In my case, oilseedradish, the seed usage should be 0.01 liters per sqm, but the HUD readout say "0.05l",
How come?
