### ISSUE TITLE
Automatic mode with VCA-GPS

### ISSUE THREAD

**Issue by nesingho** [stijnwop/proSeed#22]
Hi,

is it possible to use automatic mode with the GPS system implemented in VCA (Vehicle Control Addon) instead of Guidance Steering?

If not: is it possible to implement this as an alternative?

Many Thanks!

Nes
***

**Comment by KITT3000** [comment]
In auto mode, PS retrieves current track data from GS, unfortunately VCA does not save such data so that it can be loaded in this mode. You would need to do another counting function specifically for VCA (it is in semi-automatic mode, but uses data generated by PS), maybe if the author of the VCA added such data it could be used in automatic mode.

**Comment by nesingho** [comment]
Thanks @KITT3000  for the hint!

**Comment by Mogli12** [comment]
Hi,

VCA will add getGuidanceData and getHasGuidanceSystem to the vehicle, but only if GPS mod is not available. I hope this is ok. 

I do not feel like the snap direction of VCA is really a GPS mod. It is just a simple tool for key board players, who are too studio to drive straight (like me).

Best regards,
Stefan

**Comment by KITT3000** [comment]
@nesingho I checked and the VCA update works fine (but you cannot have the GudianceStering mod active).

**Comment by nesingho** [comment]
Hi Stefan, hi KITT3000,

I have tested build 305 of VCA -> works great with ProSeed!

Thank you very much!



> I do not feel like the snap direction of VCA is really a GPS mod. It is just a simple tool for key board players, who are too studio to drive straight (like me).

I do not need more (like Guidance Steering), because I drive rather rarely with GPS, because I mostly use a steering wheel.
Only when it really has to be absolutely straight.
And then your "micro GPS" in VCA is enough for me completely. Keep it simple, [and] stupid. ;-)

I also remember too many key combinations very badly...

Nes

**Comment by stijnwop** [comment]
Glad you found a solution that works the best for you.

Closing.
