### ISSUE TITLE
Seed usage is much higher when pre-emergence marking is toggled on

### ISSUE THREAD

**Issue by Gordon-Dry** [stijnwop/proSeed#24]
Using 1.0.0.1 from repo, dated September 13, 2020.

As visually it looks like less plants are seeded, the seed usage is about 3x higher when pre-emergence marking is on.

This is together with 
FS19_precisionFarming
FS19_realisticSeeder
FS19_RM_Seasons

**Comment by Gordon-Dry** [comment]
To make it clear:

1. It should be the other way around
2. The lower seed usage fits to normal values, even with all those mentioned mods

**Comment by Snickers125** [comment]
Did you do test this with only proSeed active?

**Comment by Gordon-Dry** [comment]
I was not able to reproduce. I guess it was a quirk.
