### ISSUE TITLE
Bug: irregular seeding

### ISSUE THREAD

**Issue by adfaexx** [stijnwop/proSeed#27]
hello there,

I don't really know how I should explain this but I think a screenshot explains better what I mean... 

![Screenshot 2021-01-19 205504](https://user-images.githubusercontent.com/77694863/105085851-a5e96f80-5a98-11eb-802a-015928fbcb11.png)

I used a modded cultivator with 4m of working width.
I used the "manual" mode. When using a 7m cultivator there was no such issue although this bug occured to me on my main playing map as this is just another map for testing.

Maybe you can help me or fix this possible bug.

**Comment by stijnwop** [comment]
You left the tramline marking on. As you can see with the two red lines.
Remember to read the manual. You only turned of pre-emergence markers which means no cultivated lanes.
