### ISSUE TITLE
Can't trun off preMarker on Kverneland DG II 12000

### ISSUE THREAD

**Issue by Snickers125** [stijnwop/proSeed#28]
It's impossible to turn off the preMakrer on the Kverneland DG II 12000.
Using the latest GitHub version of proSeed
![issue](https://user-images.githubusercontent.com/47261401/107699353-47d63380-6cb6-11eb-9178-cee55f99caa7.PNG)

**Comment by stijnwop** [comment]
It's not showing an option to turn it of in the HUD?

**Comment by Snickers125** [comment]
As you can see in the screenshots I disabled it, but it’s Premarin anyways

**Comment by sashaman** [comment]
you aren't re-planting maize by any chance, are you?

**Comment by sashaman** [comment]
as per the pic you disabled premarkers (wich are only visually) but the tramlines (ctrl-r) still active (red lines in workarea)

**Comment by Snickers125** [comment]
> you aren't re-planting maize by any chance, are you?

Nope Kverneland  DG II can’t do that. The wrong schematic in the hud must be another bug

> as per the pic you disabled premarkers (wich are only visually) but the tramlines (ctrl-r) still active (red lines in workarea)

I know, that’s the point. I disabled Pressebericht and they are still showing up as you can see on the ground tho…

**Comment by sashaman** [comment]
ok maybe i didnt explain properly lol, 
i tested and could switch it w/o any issues whatsoever
![grafik](https://user-images.githubusercontent.com/1388895/118424005-94227c80-b6c6-11eb-8981-bdf6efe394b8.png)
![grafik](https://user-images.githubusercontent.com/1388895/118424012-984e9a00-b6c6-11eb-9f27-a6e73a3e4fe7.png)
![grafik](https://user-images.githubusercontent.com/1388895/118424017-9be22100-b6c6-11eb-91fa-31c8e3a20bac.png)
![grafik](https://user-images.githubusercontent.com/1388895/118424024-a00e3e80-b6c6-11eb-9275-2c33cb1a26f7.png)
so it must be something on your side
i am under the impression you dont differentiate properly between (1) and the actualy tram line creation (red parts under equip, as seen on your picture - its active there so it creates tramlines)
![grafik](https://raw.githubusercontent.com/stijnwop/proSeed/master/docs/images/hud.png)
this is explained on the main page [OVERVIEW](https://github.com/stijnwop/proSeed#overview)....

**Comment by sashaman** [comment]
btw whats not clear from your picture, whats selected the trekker or the machine? 
CTRL-R only works with the equips elected...

**Comment by sashaman** [comment]
disabled and enabled multiple times
![grafik](https://user-images.githubusercontent.com/1388895/118425281-27f54800-b6c9-11eb-8534-436699848383.png)

**Comment by Snickers125** [comment]
So I tried the latest version and its totally fine now - this issue was old anyway
