### ISSUE TITLE
Wrong workwith on Vanilla Amazone Condor 15001

### ISSUE THREAD

**Issue by derDeBen** [stijnwop/proSeed#29]
There is an Bug in combine with the vanilla Amazone Condor 15001.
It has an workwitth of 15m but in the ProSeed window is shown 14,5m 
![fsScreen_2021_05_13_11_49_16](https://user-images.githubusercontent.com/67842747/118111439-fb4ce200-b3e3-11eb-8a90-cbbe240f27c1.png)
![fsScreen_2021_05_13_11_49_04](https://user-images.githubusercontent.com/67842747/118111443-fe47d280-b3e3-11eb-9947-144533ce2bb3.png)

**Comment by sashaman** [comment]
not a bug, but giants fault
![grafik](https://user-images.githubusercontent.com/1388895/118365660-09def900-b59e-11eb-99f4-5e9b2d4ee032.png)
![grafik](https://user-images.githubusercontent.com/1388895/118365664-0d728000-b59e-11eb-97fb-7ec974940103.png)
7.5 + 7 = 14.5  😄

**Comment by derDeBen** [comment]
Thanks Giants ... :)
