### ISSUE TITLE
Problem with Lanes

### ISSUE THREAD

**Issue by BarnyHarz** [stijnwop/proSeed#3]
Hello Wopster,

first a very big thank you from me for this script. I loved ProSeed mod in FS17 and now you brought it to FS19.
I downloaded it today and as always with new mods I did some testing and found a little issue.
I tried the auto mode with a seeding machine 6m working width for 24m working width of sprayer. I had a look in the linked pdf and saw that i have to do one and a half lane before i doe the drivelane in the third. My problem now is, that in auto mode the system always activates the drive laner in the second lane and not in the third. I did as you described it in the readme. maybe it is just a bug with the seeding machine, but i tried it with a 3m seeding machine and it is the same problem. The drive laner gets activated one lane to early in auto mode. Maybe I did something wrong but when I have a sprayer with 24m working width i need 12m distance to the field edge. So one full lane, one half lane and the second half of the lane with drive laner makes 12m. The problem is only with the first drive lane. The second drive lane is placed right, because i can drive the third and fourth lane and then start again at the number one and at 2 the drive  laner is activated again.

Kind regards

Barnabas

**Comment by Evilman2517** [comment]
You probably didn't zeroed the first lane. I just tested ProSeed (3m seeder to 24m sprayer) and everything worked fine

**Comment by stijnwop** [comment]
Well there was a rounding issue I introduce not long before I submitted it to ModHub a month ago.

I fixed it this evening, could you download the latest from here (GitHub) and try again according to the pdf

**Comment by BarnyHarz** [comment]
I will try. And i just had a discussion on discord. AgrarPlay mentioned to drive the half lane in manual mode and then start with the first full lane in automatic mode at the edge of the half lane. This seems to be a simple solution for this issue

**Comment by BarnyHarz** [comment]
Latest version from Github works perfect in automatic mod. Thank you for your awesome mods. Kepp up the good work. :)
