### ISSUE TITLE
Original precision seed drills direct seeding

### ISSUE THREAD

**Issue by Gr0lix** [stijnwop/proSeed#30]
Hi 

Is it intended that direct sowing is added to all Giants precision air seeders (see Pic)? Mods or DLC pecision air seeder don't have this.

![Pic](https://user-images.githubusercontent.com/86199927/122681817-76c95c80-d1f6-11eb-8387-dc8354dfa491.jpg)

**Comment by Snickers125** [comment]
That's intended - should work on all planters (not seeders!) with the newest commit.

**Comment by Gr0lix** [comment]
Okay, thanks for the hint.
