### ISSUE TITLE
I have lost the menu

### ISSUE THREAD

**Issue by oliverbosslol** [stijnwop/proSeed#31]
Idk where the menu went on my screen!

**Comment by stijnwop** [comment]
Check the other issues https://github.com/stijnwop/proSeed/issues/23

🙂

**Comment by oliverbosslol** [comment]
?? Wdym?

**Comment by KITT3000** [comment]
@oliverbosslol you are using the old version, in the newest version it has long been fixed, go to the topic provided by wopster and you will learn how to download the latest version
