### ISSUE TITLE
Option to turn off tramlines

### ISSUE THREAD

**Issue by chrissnave** [stijnwop/proSeed#32]
I'm trying to plant a cover crop (oil seed radish) & I won't be fertilizing this later. So there's no need to make tramlines when planting this crop. But I don't see a way to turn off tramlines other than set the width to a very high number.

**Comment by chrissnave** [comment]
Nevermind, just figured out I can use manual mode when using a helper if I don't want to make tramlines.

**Comment by stijnwop** [comment]
I wrote a readme file in the root of this project that describes this too. :)
