### ISSUE TITLE
Lost the hud

### ISSUE THREAD

**Issue by oliverbosslol** [stijnwop/proSeed#33]
![Farming Simulator 19 09_07_2021 16_44_12](https://user-images.githubusercontent.com/80633164/125104207-04e98200-e0d5-11eb-92fc-122f55ca73fb.png)

Where is the hud?

**Comment by oliverbosslol** [comment]
Idk where the hud went

**Comment by KITT3000** [comment]
You are using the old version of the mod, you need to download the latest version from this page (more info here: #23)

**Comment by oliverbosslol** [comment]
Ok thx
