### ISSUE TITLE
Game not detecting mod

### ISSUE THREAD

**Issue by Thomas-Valkenburg** [stijnwop/proSeed#35]
I recently downloaded the development version (through this github), but the game won't seem to detect the mod.

I tried unpacking and repacking as stated in #23

@KITT3000:
> @Crixy-power In the "code" tab, you need to download the entire repository (green button on the right) and unpack it and pack it into a new ZIP archive.

How would I install it so that it's usable in game?

**Comment by KITT3000** [comment]
did you pack the contents of the folder or folder?

**Comment by Thomas-V1** [comment]
I zipped the folder itself.

The file was named proSeed and proSeed-master (depending on if you cloned or downloaded the zip file)

I tried leaving the name to default when zipping (proSeed.zip, proSeed-master.zip), but also FS19_proSeed.zip

**Comment by KITT3000** [comment]
you need to zip the contents of the folder (enter the folder, ctrl + a, add it to the zip archive and name it FS19_proSeed)
