### ISSUE TITLE
Bug: Incompatible with courseplay.

### ISSUE THREAD

**Issue by talianagisan** [stijnwop/proSeed#42]
When you attempt to do a seeding course with courseplay the moment it tries to seed, it considers the job finished and packs up and finishes. Only does this with proseed enabled. Verified its not another mod by starting a new save with just proseed and courseplay.

**Comment by Snickers125** [comment]
Does that issue occur in any mode (like manual, semi, auto) of ProSeed?

**Comment by Lactic68** [comment]
Just tested with CP 7.0.1.5 and it works well with ProSeed on Manual mode engaged.

**Comment by talianagisan** [comment]
It doesn't work in any mode. I'll try and re test it later today.

**Comment by talianagisan** [comment]
Update: Courseplay decided to turn fertilize with sowing machine ( I don't do that) back on for some reason (update likely did it) so it kept thinking it was out of fertilizer. Partial user error part unexpected setting switch.

**Comment by Lactic68** [comment]
I think this issue can be solved now @Snickers125 :)
