### ISSUE TITLE
Hud dont open

### ISSUE THREAD

**Issue by Phips99** [stijnwop/proSeed#7]
Hello,

i have the problem, that the HUD isnt show. I dont know why. I downloaded it via modhub an updated it to 1.0.0.1 

Please Help

**Comment by KITT3000** [comment]
1. Download the repository (there is a fix after 1.0.0.1) and repack it to a new ZIP archive and replace it in the folder with the modem.
2. Go to the folder with your save, find the file `proSeed.xml` and change its X and Y position values to 0.5 and save.
3. Run the game

**Comment by stijnwop** [comment]
[FS19_proSeed.zip](https://github.com/stijnwop/proSeed/files/4831967/FS19_proSeed.zip)

(For those who don't know how to get it from the repo and re-zip.

**Comment by Jaiimez** [comment]
> [FS19_proSeed.zip](https://github.com/stijnwop/proSeed/files/4831967/FS19_proSeed.zip)
> 
> (For those who don't know how to get it from the repo and re-zip.

I downloaded via the link you provided, and edited the proSeed.xml file as instructed, and i'm still seeing no HUD.

**Comment by zakkstorey1** [comment]
I have done these procedures and still no HUD

**Comment by stijnwop** [comment]
@Jaiimez @zakkstorey1 then I would like to see the log and your savegame.

**Comment by Evilman2517** [comment]
Regarding this issue I noticed a proSeed.xml file in the savegame folder on my dedi server with only one entry. We are five to six players on this server. At least two players already used proSeed on this Savegame. Whose postion is saved in there? Could this be related?

**Comment by stijnwop** [comment]
@Evilman2517 on Dedi only the position will be used for initial startup for all clients. Then each client has the freedom to move them.

Problem could be that its indeed an older proSeed xml file with corrupted positions.

**Comment by dastdsjas** [comment]
Hi I had same problem had to download the above link, delete proseed from mods open the game go into my saved game a pop up said proseed was in the saved file but the mod isnt available  hit continue then exited the game completely, put new down load in mod file , restart the game then select the mod asper normal for new mod then there it was in my game 

Hope this helps

**Comment by alin-pixel** [comment]
> Hi I had same problem had to download the above link, delete proseed from mods open the game go into my saved game a pop up said proseed was in the saved file but the mod isnt available hit continue then exited the game completely, put new down load in mod file , restart the game then select the mod asper normal for new mod then there it was in my game
> 
> Hope this helps

It worked for me as well, thank you!

**Comment by svnissen** [comment]
> 
> 
> Hi I had same problem had to download the above link, delete proseed from mods open the game go into my saved game a pop up said proseed was in the saved file but the mod isnt available hit continue then exited the game completely, put new down load in mod file , restart the game then select the mod asper normal for new mod then there it was in my game
> 
> Hope this helps

Thanks to dastdsjas! This is procedure solved my HUD problem too. Thanks for sharing, and many thanks to the developers who put blood and sweat in this mod :-D. Keep up going!

**Comment by Gordon-Dry** [comment]
How about merging all those fixes from several issues to the branch instead of making the users who find their way to this place to manually edit stuff to fix?

**Comment by KITT3000** [comment]
@Gordon-Dry but it's already in the default branch, all you have to do is download the repository and repack it into a new zip archive

**Comment by stijnwop** [comment]
It's marked fixed.. should tell enough. 

Lets also close this before someone else starts shouting things too. :)

**Comment by Gordon-Dry** [comment]
Well, the latest merged pull requests were translations and readmes...

Okay, the commits... latest Sept 13, 2020

But why no release then?

And even why not put in on modhoster anyway when it's clear that it "should" work for months?

**Comment by stijnwop** [comment]
Cause there's more to life than modding.. perhaps you should try it yourself. I have many more projects that need attention.

**Comment by Gordon-Dry** [comment]
Thank you for insulting me. I was doing (participating) some modding on Github for Kerbalism and I know how to merge stuff and make stuff happen within a couple of minutes. But well then... at least you have time to reply and close issues.

**Comment by stijnwop** [comment]
There's no insult men.. not sure what your problem is. But you seem to want to make one.

Have a great day.
